src/main/java/com/yxb/cms/domain/vo/AnnouncementInfo.java
/**
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2017 © yangxiaobing, 873559947@qq.com
 *
 * This file is part of contentManagerSystem.
 * contentManagerSystem is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * contentManagerSystem is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with contentManagerSystem.  If not, see <http://www.gnu.org/licenses/>.
 *
 * 这个文件是contentManagerSystem的一部分。
 * 您可以单独使用或分发这个文件，但请不要移除这个头部声明信息.
 * contentManagerSystem是一个自由软件，您可以自由分发、修改其中的源代码或者重新发布它，
 * 新的任何修改后的重新发布版必须同样在遵守GPL3或更后续的版本协议下发布.
 * 关于GPL协议的细则请参考COPYING文件，
 * 您可以在contentManagerSystem的相关目录中获得GPL协议的副本，
 * 如果没有找到，请连接到 http://www.gnu.org/licenses/ 查看。
 *
 * - Author: yangxiaobing
 * - Contact: 873559947@qq.com
 * - License: GNU Lesser General Public License (GPL)
 * - source code availability: http://git.oschina.net/yangxiaobing_175/contentManagerSystem
 */
package com.yxb.cms.domain.vo;

import com.yxb.cms.architect.utils.DateUtil;
import com.yxb.cms.domain.dto.PageDto;

import java.io.Serializable;
import java.util.Date;
/**
 * 站内公告信息表
 * @author yangxiaobing
 * @date  2017/9/1
 *
 */
public class  AnnouncementInfo extends PageDto implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_announcement_info.announcement_id
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    private Integer announcementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_announcement_info.announcement_type
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    private Integer announcementType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_announcement_info.announcement_title
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    private String announcementTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_announcement_info.announcement_content
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    private String announcementContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_announcement_info.announcement_author
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    private String announcementAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_announcement_info.announcement_time
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    private Date announcementTime;



    private String beginTime;

    private String endTime;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_announcement_info.announcement_id
     *
     * @return the value of cc_announcement_info.announcement_id
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    public Integer getAnnouncementId() {
        return announcementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_announcement_info.announcement_id
     *
     * @param announcementId the value for cc_announcement_info.announcement_id
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    public void setAnnouncementId(Integer announcementId) {
        this.announcementId = announcementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_announcement_info.announcement_type
     *
     * @return the value of cc_announcement_info.announcement_type
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    public Integer getAnnouncementType() {
        return announcementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_announcement_info.announcement_type
     *
     * @param announcementType the value for cc_announcement_info.announcement_type
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    public void setAnnouncementType(Integer announcementType) {
        this.announcementType = announcementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_announcement_info.announcement_title
     *
     * @return the value of cc_announcement_info.announcement_title
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    public String getAnnouncementTitle() {
        return announcementTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_announcement_info.announcement_title
     *
     * @param announcementTitle the value for cc_announcement_info.announcement_title
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    public void setAnnouncementTitle(String announcementTitle) {
        this.announcementTitle = announcementTitle == null ? null : announcementTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_announcement_info.announcement_content
     *
     * @return the value of cc_announcement_info.announcement_content
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    public String getAnnouncementContent() {
        return announcementContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_announcement_info.announcement_content
     *
     * @param announcementContent the value for cc_announcement_info.announcement_content
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    public void setAnnouncementContent(String announcementContent) {
        this.announcementContent = announcementContent == null ? null : announcementContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_announcement_info.announcement_author
     *
     * @return the value of cc_announcement_info.announcement_author
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    public String getAnnouncementAuthor() {
        return announcementAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_announcement_info.announcement_author
     *
     * @param announcementAuthor the value for cc_announcement_info.announcement_author
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    public void setAnnouncementAuthor(String announcementAuthor) {
        this.announcementAuthor = announcementAuthor == null ? null : announcementAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_announcement_info.announcement_time
     *
     * @return the value of cc_announcement_info.announcement_time
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    public Date getAnnouncementTime() {
        return announcementTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_announcement_info.announcement_time
     *
     * @param announcementTime the value for cc_announcement_info.announcement_time
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    public void setAnnouncementTime(Date announcementTime) {
        this.announcementTime = announcementTime;
    }


    public String getBeginTime() {
        return beginTime;
    }

    public void setBeginTime(String beginTime) {
        this.beginTime = beginTime;
    }

    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }
    /**
     * 公告日期格式化
     * @return
     */
    public String getAnnouncementTime_Lable(){
        if(this.getAnnouncementTime() != null){
            return DateUtil.Date2Stirng2Second(announcementTime);
        }
        return "";
    }

    /**
     * 公告类型格式化
     * @return
     */
    public String getAnnouncementType_Lable(){
        if(this.getAnnouncementType() != null && this.getAnnouncementType().intValue() == 1){
            return "系统公告";
        }else if(this.getAnnouncementType() != null && this.getAnnouncementType().intValue() == 2){
            return "活动公告";
        }else{
            return "";
        }

    }
}

src/main/java/com/yxb/cms/controller/system/AnnouncementInfoController.java
/**
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * <p>
 * Copyright 2017 © yangxiaobing, 873559947@qq.com
 * <p>
 * This file is part of contentManagerSystem.
 * contentManagerSystem is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * <p>
 * contentManagerSystem is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * <p>
 * You should have received a copy of the GNU Lesser General Public License
 * along with contentManagerSystem.  If not, see <http://www.gnu.org/licenses/>.
 * <p>
 * 这个文件是contentManagerSystem的一部分。
 * 您可以单独使用或分发这个文件，但请不要移除这个头部声明信息.
 * contentManagerSystem是一个自由软件，您可以自由分发、修改其中的源代码或者重新发布它，
 * 新的任何修改后的重新发布版必须同样在遵守GPL3或更后续的版本协议下发布.
 * 关于GPL协议的细则请参考COPYING文件，
 * 您可以在contentManagerSystem的相关目录中获得GPL协议的副本，
 * 如果没有找到，请连接到 http://www.gnu.org/licenses/ 查看。
 * <p>
 * - Author: yangxiaobing
 * - Contact: 873559947@qq.com
 * - License: GNU Lesser General Public License (GPL)
 * - source code availability: http://git.oschina.net/yangxiaobing_175/contentManagerSystem
 */
package com.yxb.cms.controller.system;

import com.yxb.cms.architect.constant.BussinessCode;
import com.yxb.cms.architect.utils.BussinessMsgUtil;
import com.yxb.cms.controller.BasicController;
import com.yxb.cms.dao.AnnouncementInfoMapper;
import com.yxb.cms.domain.bo.BussinessMsg;
import com.yxb.cms.domain.vo.AnnouncementInfo;
import com.yxb.cms.service.AnnouncementInfoService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;


/**
 * 公告管理Controller
 *
 * @author yangxiaobing
 * @date 2017/9/1
 */
@Controller
@RequestMapping("announcement")
public class AnnouncementInfoController extends BasicController {


    @Autowired
    private AnnouncementInfoService announcementInfoService;

    @Autowired
    private AnnouncementInfoMapper announcementInfoMapper;

    /**
     *跳转到公告列表页面
     * @return
     */
    @RequestMapping("/announcement_list.do")
    public String toAnnouncementListPage() {
        return "system/announcement_list";
    }

    /**
     * 公告列表List
     * @param announcement 公告实体
     * @return
     */
    @RequestMapping("/ajax_announcement_list.do")
    @ResponseBody
    public String ajaxUserList(AnnouncementInfo announcement) {
        return announcementInfoService.selectAnnInfoResultPageList(announcement);
    }

    /**
     *跳转到公告新增页面
     * @return
     */
    @RequestMapping("/announcement_add.do")
    public String toAnnouncementAddPage() {
        return "system/announcement_add";
    }

    /**
     * 保存公告信息
     * @param announcementType      公告类型
     * @param announcementTitle     公告标题
     * @param announcementContent   公告内容
     * @return
     */
    @RequestMapping("/ajax_save_announcement.do")
    @ResponseBody
    public BussinessMsg ajaxSaveAnnouncement(Integer announcementType, String announcementTitle,String announcementContent){
        try {
            return announcementInfoService.saveAnnouncementInfo(announcementType,announcementTitle,announcementContent,this.getCurrentLoginName());
        } catch (Exception e) {
            log.error("保存公告信息方法内部错误",e);
            return BussinessMsgUtil.returnCodeMessage(BussinessCode.ANNOUNCEMENT_SAVE_ERROR);
        }
    }

    /**
     * 公告详情页面
     * @param model
     * @param announcementId 公告Id
     * @return
     */
    @RequestMapping("/announcement_detail.do")
    public String toAnnouncementDetailPage(Model model, Integer announcementId) {
        AnnouncementInfo announcementInfo = announcementInfoService.selectAnnouncementInfoById(announcementId);
        model.addAttribute("announcementInfo",announcementInfo);
        return "system/announcement_detail";
    }

    /**
     * 删除公告
     * @param announcementId 公告Id
     * @return
     */
    @RequestMapping("/ajax_del_announcement.do")
    @ResponseBody
    public BussinessMsg ajaxDelAnnouncement(Integer announcementId){
        try {
            return announcementInfoService.deleteAnnouncementInfo(announcementId);
        } catch (Exception e) {
            log.error("删除公告信息方法内部错误",e);
            return BussinessMsgUtil.returnCodeMessage(BussinessCode.ANNOUNCEMENT_DEL_ERROR);
        }
    }

    /**
     * 查询用户未读公告信息
     * @return
     */
    @RequestMapping("/ajax_unread_anninfo_count.do")
    @ResponseBody
    public  Integer ajaxUnreadAnnInfoCount(){
        if(null != this.getCurrentLoginId()){
            Long unReadCount = announcementInfoMapper.selectUnreadAnnInfoCountByUserId(this.getCurrentLoginId());
            return unReadCount.intValue();
        }
        return 0;

    }
    /**
     * 查询用户已读公告信息
     * @return
     */
    @RequestMapping("/ajax_read_anninfo_count.do")
    @ResponseBody
    public  Integer ajaxReadAnnInfoCount(){
        if(null != this.getCurrentLoginId()){
            Long readCount = announcementInfoMapper.selectReadAnnInfoCountByUserId(this.getCurrentLoginId());
            return readCount.intValue();
        }
        return 0;

    }
    /**
     * 查询全部公告信息
     * @return
     */
    @RequestMapping("/ajax_allread_anninfo_count.do")
    @ResponseBody
    public  Integer ajaxAllReadAnnInfoCount(){
        Long allReadCount = announcementInfoMapper.selectAllReadAnnInfoCount();
        return allReadCount.intValue();

    }


    /**
     *跳转到未读公告列表页面
     * @return
     */
    @RequestMapping("/announcement_unread_list.do")
    public String toAnnouncementUnReadListPage() {
        return "system/announcement_unread_list";
    }

    /**
     * 未读公告列表List
     * @return
     */
    @RequestMapping("/ajax_unread_anninfo_list.do")
    @ResponseBody
    public String ajaxUnReadAnnInfoList() {
        return announcementInfoService.selectUnreadAnnInfoListByUserId(this.getCurrentLoginId());
    }
    /**
     * 已读公告列表List
     * @return
     */
    @RequestMapping("/ajax_read_anninfo_list.do")
    @ResponseBody
    public String ajaxReadAnnInfoList() {
        return announcementInfoService.selectReadAnnInfoListByUserId(this.getCurrentLoginId());
    }
    /**
     * 全部公告列表List
     * @return
     */
    @RequestMapping("/ajax_allread_anninfo_list.do")
    @ResponseBody
    public String ajaxAllReadAnnInfoList() {
        return announcementInfoService.selectAllReadAnnInfoListByUserId();
    }

    /**
     * 公告信息标记为已读
     * @param announcementId 公告Id
     * @return
     */
    @RequestMapping("/ajax_ins_read_anninfo_user.do")
    @ResponseBody
    public BussinessMsg ajaxReadAnnUserInfo(Integer announcementId){
        try {
            return announcementInfoService.insertReadAnnUserInfo(announcementId,this.getCurrentLoginId());
        } catch (Exception e) {
            log.error("公告信息标记为已读处理方法内部错误",e);
            return BussinessMsgUtil.returnCodeMessage(BussinessCode.ANNOUNCEMENT_USER_INSERT_ERROR);
        }
    }

    /**
     * 公告信息全部标记为已读
     * @param announcementIds 公告Ids
     * @return
     */
    @RequestMapping("/ajax_ins_allread_anninfo_user.do")
    @ResponseBody
    public BussinessMsg ajaxAllReadAnnUserInfo(@RequestParam(value = "announcementIds[]") Integer[] announcementIds){
        try {
            return announcementInfoService.insertAllReadAnnUserInfo(announcementIds, this.getCurrentLoginId());
        } catch (Exception e) {
            log.error("公告信息标记为已读处理方法内部错误",e);
            return BussinessMsgUtil.returnCodeMessage(BussinessCode.ROLE_FAILK_ERROR);
        }
    }
}

src/main/webapp/WEB-INF/views/system/announcement_add.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@include file="/comm/mytags.jsp" %>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>后台管理系统</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="keywords" content="后台管理系统">
    <meta name="description" content="致力于提供通用版本后台管理解决方案">
    <link rel="shortcut icon" href="${ctx}/static/img/favicon.ico">

    <link rel="stylesheet" href="${ctx}/static/layui_v2/css/layui.css">


    <script src="${ctx}/static/layui_v2/layui.js"></script>
    <script src="${ctx}/static/layui_v2/layui.js"></script>
    <script src="${ctx}/static/layui_v2/layui.js"></script>

</head>
<body class="childrenBody" style="font-size: 12px;margin: 10px 10px 0;">
<form class="layui-form layui-form-pane">

    <div class="layui-form-item">
        <label class="layui-form-label">公告标题</label>
        <div class="layui-input-block">
            <input type="text" class="layui-input" name="announcementTitle" lay-verify="required" maxlength="50"  placeholder="请输入公告标题">
        </div>
    </div>
    <div class="layui-form-item" >
        <label class="layui-form-label">公告类型</label>
        <div class="layui-input-block">
            <select  name="announcementType" lay-verify="required">
                <option value="">请选择</option>
                <option value="1">1-系统公告</option>
                <option value="2">2-活动公告</option>
            </select>
        </div>
    </div>
    <div class="layui-form-item layui-form-text">
        <label class="layui-form-label">公告内容</label>
        <div class="layui-input-block">
            <textarea id="announcementContentEdit" style="display: none;" ></textarea>
        </div>
    </div>
    <div class="layui-form-item" style="text-align: center;">
            <button class="layui-btn" lay-submit="" lay-filter="saveAnnouncement">保存</button>
            <button type="layui-btn" id="cancle" class="layui-btn layui-btn-primary">取消</button>

    </div>
</form>
<script type="text/javascript">
    layui.config({
        base : "${ctx}/static/js/"
    }).use(['form','layer','jquery','common','layedit'],function(){
        var $ = layui.$,
                form = layui.form,
                common = layui.common,
                layedit = layui.layedit,
                layer = parent.layer === undefined ? layui.layer : parent.layer;

        /**建立编辑器*/
        var index = layedit.build('announcementContentEdit',{
            height: 120, //设置编辑器高度
            tool: ['strong', 'italic', 'underline', 'del','|','left','center','right','|','link','unlink','face']

        });


        /**保存公告信息**/
        form.on("submit(saveAnnouncement)",function(data){
            if($.trim(layedit.getText(index)).length <= 0){
                common.cmsLayErrorMsg("请输入公告内容")
                return false;
            }
            if(layedit.getContent(index).length >500){
                common.cmsLayErrorMsg("公告内容长度超出限制,当前长度:"+layedit.getContent(index).length+",最大长度:500")
                return false;
            }
            var loading = top.layer.msg('数据提交中，请稍候',{icon: 16,time:false,shade:0.8});
            $.ajax({
                url : '${ctx}/announcement/ajax_save_announcement.do',
                type : 'post',
                async: false,
                data : {
                    announcementType:data.field.announcementType,
                    announcementTitle:data.field.announcementTitle,
                    announcementContent:layedit.getContent(index)
                },
                success : function(data) {
                    if(data.returnCode == 0000){
                        top.layer.close(loading);
                        common.cmsLaySucMsg("公告信息保存成功！");
                        var index = parent.layer.getFrameIndex(window.name); //先得到当前iframe层的索引
                        parent.layer.close(index); //再执行关闭                        //刷新父页面
                        parent.location.reload();
                    }else{
                        top.layer.close(loading);
                        common.cmsLayErrorMsg(data.returnMessage);
                    }
                },error:function(data){
                    top.layer.close(index);

                }
            });
            return false;
        });

        /**取消*/
        $("#cancle").click(function(){
            var index = parent.layer.getFrameIndex(window.name); //先得到当前iframe层的索引
            parent.layer.close(index); //再执行关闭
        });

    });

</script>
</body>
</html>

src/main/webapp/WEB-INF/views/system/announcement_detail.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@include file="/comm/mytags.jsp" %>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>后台管理系统</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="keywords" content="后台管理系统">
    <meta name="description" content="致力于提供通用版本后台管理解决方案">

    <link rel="shortcut icon" href="${ctx}/static/img/favicon.ico">
    <link rel="stylesheet" href="${ctx}/static/layui_v2/css/layui.css">
    <link rel="stylesheet" type="text/css" href="${ctx}/static/css/personal.css" media="all">
    <link rel="stylesheet" type="text/css" href="http://at.alicdn.com/t/font_9h680jcse4620529.css">
    <script src="${ctx}/static/layui_v2/layui.js"></script>


<body>
<div class="larry-grid layui-anim layui-anim-upbit larryTheme-A ">
    <div class="larry-personal">
        <div class="layui-tab">

            <div class="larry-separate"></div>
            <!-- 公告列表 -->
            <div class="layui-tab-item layui-show" style="padding: 10px 15px;">
                <div class="layui-elem-quote layui-quote-nm" style="border-width: 1px;">
                    <span style="display:inline-block;width:100%;text-align:center; font-size:25px;">${announcementInfo.announcementTitle}</span>
                    <span style="display:inline-block;width:100%;text-align:center;color:#999999;margin-top: 22px;font-size: 14px; ">
                        <label style="margin-right: 20px;">公告类型：${announcementInfo.announcementType_Lable}</label>
                        <label style="margin-right: 20px;">发布时间：${announcementInfo.announcementTime_Lable}</label>
                        <label style="margin-right: 20px;">发布者:${announcementInfo.announcementAuthor}</label>
                    </span>
                    <hr class="layui-bg-green">
                    <div>
                        <p style="font-size: 14px;line-height: 22px;">尊敬的用户：</p>
                        <br>
                        <p style="margin-left:12px;font-size: 14px;line-height: 22px;">${announcementInfo.announcementContent}</p >

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<script type="text/javascript">
</script>
</body>
</html>

src/main/webapp/WEB-INF/views/system/res_tree_list.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@include file="/comm/mytags.jsp" %>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>后台管理系统</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="keywords" content="后台管理系统">
    <meta name="description" content="致力于提供通用版本后台管理解决方案">
    <link rel="shortcut icon" href="${ctx}/static/img/favicon.ico">

    <link rel="stylesheet" href="${ctx}/static/layui_v2/css/layui.css">
    <link rel="stylesheet" href="${ctx}/static/css/global.css">

    <link rel="stylesheet" type="text/css" href="${ctx}/static/css/common.css" media="all">
    <link rel="stylesheet" type="text/css" href="${ctx}/static/css/personal.css" media="all">
    <link rel="stylesheet" type="text/css" href="http://at.alicdn.com/t/font_9h680jcse4620529.css">


    <script src="${ctx}/static/layui_v2/layui.js"></script>
    <script type="text/javascript" src="${ctx}/static/js/gtf.js"></script>






<body>

<div class="table-list">
    <table class="layui-table" id="tabletree">
        <colgroup>
            <col width="150">
            <col width="150">
            <col width="200">
            <col width="200">
        </colgroup>
        <thead>
        <tr>
            <th>菜单名称</th>
            <th>菜单操作</th>
            <th>菜单状态</th>
            <th>菜单状态</th>
        </tr>
        </thead>
        <tbody>
        <tr data-tb-pid="0" data-tb-id="1">
            <td>系统应用</td>
            <td>/</td>
            <td>启用</td>
            <td>启用</td>
        </tr>
        <tr data-tb-pid="1" data-tb-id="13">
            <td>首页管理</td>
            <td>/</td>
            <td>启用</td>
            <td>启用</td>
        </tr>
        <tr data-tb-pid="13" data-tb-id="6">
            <td>后台首页</td>
            <td>Index/home</td>
            <td>启用</td>
            <td>启用</td>
        </tr>
        <tr data-tb-pid="1" data-tb-id="33">
            <td>管理员管理</td>
            <td>/</td>
            <td>启用</td>
            <td>启用</td>
        </tr>

        </tbody>
    </table>
</div>



</body>
</html>
<script type="text/javascript">


</script>